# Generated by Django 4.1.3 on 2022-11-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dht',
            name='hum',
            field=models.FloatField(null=True),
        ),
    ]
